name: mnemoszune
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  llm_server_dart:
    git:
      url: https://github.com/boapps/llm_server.dart
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.19
  path_provider: ^2.1.2
  path: ^1.8.3
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  file_picker: ^10.0.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  langchain: ^0.7.7+2
  langchain_chroma: ^0.2.1+5
  langchain_core: ^0.3.6+1
  langchain_community: ^0.3.3
  langchain_openai: ^0.7.3
  syncfusion_flutter_pdf: ^29.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
