name: mnemoszune
description: "A Flutter project for storing quizzes and class materials."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  drift: ^2.0.0
  drift_flutter: ^2.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  drift_dev: ^2.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true